# Generated by Django 2.0.2 on 2018-02-18 02:55

import functools

from django.db import migrations, models

import moviecine.models


class Migration(migrations.Migration):
    dependencies = [
        ('moviecine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.FileField(upload_to=functools.partial(moviecine.models.make_filepath, *('actors',), **{})),
        ),
    ]
