# Generated by Django 2.0.2 on 2018-02-18 03:19

import functools

from django.db import migrations, models

import moviecine.models


class Migration(migrations.Migration):
    dependencies = [
        ('moviecine', '0003_auto_20180217_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.FileField(upload_to=functools.partial(moviecine.models.make_filepath, *('movies',), **{})),
        ),
    ]
