# Generated by Django 2.0.2 on 2018-02-18 22:41

import functools

from django.db import migrations, models

import moviecine.models


class Migration(migrations.Migration):
    dependencies = [
        ('moviecine', '0005_auto_20180218_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.ImageField(blank=True,
                                    upload_to=functools.partial(moviecine.models.make_filepath, *('actors',), **{})),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.FileField(blank=True,
                                   upload_to=functools.partial(moviecine.models.make_filepath, *('movies',), **{})),
        ),
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
