# Generated by Django 2.0.2 on 2018-02-19 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('moviecine', '0008_auto_20180218_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ['nome']},
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='image',
            new_name='imagem',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='year',
            new_name='ano',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='actors',
            new_name='atores',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='duration',
            new_name='duracao',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='image',
            new_name='imagem',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='published',
            new_name='publicado',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='synopsis',
            new_name='sinopse',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='original_title',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='title',
            new_name='titulo_original',
        ),
    ]
