# Generated by Django 2.0.2 on 2018-02-19 00:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('moviecine', '0009_auto_20180218_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='titulo',
            new_name='titulo_a',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='titulo_original',
            new_name='titulo_original_a',
        ),
    ]
