# Generated by Django 2.0.2 on 2018-02-19 00:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('moviecine', '0011_auto_20180218_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='titulo_a',
            new_name='titulo_original',
        ),
    ]
